// Developer Express Code Central Example:
// How to show items of the child categories in the list of items of the parent category when using the CategorizedListEditor
// 
// The CategorizedListEditor consist of two views - the tree list of the categories
// in the left area of the editor (CategoriesListView), and the list of categorized
// items on the right (GridView). Items in the GridView are filtered by category,
// selected in the CategoriesListView. If the selected category has children, items
// belonging to them won't be shown in the GridView. This example demonstrates, how
// to change this behavior, and filter GridView to show all items of the selected
// category and its children. See Also: Implement the ICategorizedItem Interface
// Use the Built-in HCategory Class How to: Implement a Custom Windows Forms List
// Editor
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E1415

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinSample.Win.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
